config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  root 'contacts#index'

  get 'login' => 'account#form'
  post 'login' => 'account#login'

  get 'register' => 'account#register_form'
  post 'register' => 'account#register'

  get 'logout' => 'account#logout'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  @per_page = 5
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/account_controller.rb
class AccountController < ActionController::Base
  layout 'application'

  def form
    @user = User.new
  end

  def login
    user = User.find_by_username(login_params[:username])
    if user and user.authenticate(login_params[:password])
      session[:current_user_id] = user.id
      flash[:error] = ''
      redirect_to contacts_path
    else
      flash[:error] = 'Błędny login'
      render :form, :status => :bad_request
    end
  end

  def register_form
    @user = User.new
  end

  def register
    @user = User.new(register_params)
    if @user.valid?
      @user.save
      flash[:success] = 'Twoje konto zostało zarejestrowane. Teraz możesz się zalogować.  '
      redirect_to login_path
    else
      render :register_form, :status => :bad_request
    end
  end

  def logout
    @_current_user = session[:current_user_id] = nil
    redirect_to login_path
  end

  private
  def login_params
    params.permit(:username, :password)
  end

  def register_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ActionController::Base
  layout 'application'
  before_action :check_if_logged
  before_action :check_contact, only: [:edit, :update, :destroy]

  def index
    if params[:search]
      @contacts = Contact.where(
          'users_id=? AND (first_name like ? OR last_name like ? OR phone_number like ? OR street like ? OR city like ?
           OR post_code like ? OR number like ? OR email like ?)',
          @user.id, "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%, %#{params[:search]}%",
          "%#{params[:search]}%", "%#{params[:search]}%","%#{params[:search]}%", "%#{params[:search]}%",
          "%#{params[:search]}%"
      ).paginate(:page => params[:page])
      @search_param = params[:search]
    else
      @contacts = Contact.where(users_id: @user.id).paginate(:page => params[:page])
    end
  end

  def new
    @contact = Contact.new(users_id: @user.id)
  end

  def create
    @contact = Contact.create(contact_params)
    flash[:success] = 'Kontakt dodano pomyślnie'
    redirect_to contacts_path
  end

  def edit
  end

  def update
    @contact.update(contact_params)
    flash[:success] = 'Kontakt edytowano pomyślnie'
    redirect_to contacts_path
  end

  def destroy
    @contact.destroy
    flash[:success] = 'Kontakt usunięto pomyślnie'
    redirect_to contacts_url
  end

  private
    def check_if_logged
      if session[:current_user_id]
        @user = User.find(session[:current_user_id])
      else
        redirect_to :controller => 'account', :action => 'form'
      end
    end

    def check_contact
      @contact = Contact.find(params[:id])
      if @contact.users_id != session[:current_user_id]
        render :nothing => true, response_code => 400
      end
    end

    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone_number,
                                      :email, :city, :street, :number, :post_code, :users_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/edit.html.erb
<%= bootstrap_form_for(@contact) do |f| %>
    <%= f.hidden_field :users_id %>
    <%= f.text_field :first_name, label: 'Imię' %>
    <%= f.text_field :last_name, label: 'Nazwisko' %>
    <%= f.phone_field :phone_number, label: 'Nr telefonu' %>
    <%= f.email_field :email, label: 'Email' %>
    <%= f.text_field :street, label: 'Ulica' %>
    <%= f.text_field :number, label: 'Nr domu' %>
    <%= f.text_field :post_code, label: 'Kod pocztowy' %>
    <%= f.text_field :city, label: 'Miejscowość' %>
    <%= f.submit 'Edytuj' %>
    <%= link_to 'Powrót', contacts_path, class: 'btn btn-default' %>
<% end %>

app/views/contacts/index.html.erb
<div class="pull-right" style="margin-bottom: 10px">
  <form class="form-inline">
      <label for="search">Wyszukiwanie: </label>
      <input id="search" type="text" name="search" value="<%= @search_param %>"/>
      <input class="btn btn-default" type="submit" value="Szukaj"/>
  </form>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Numer telefonu</th>
      <th>Email</th>
      <th>Adres</th>
      <th>Akcje</th>
    </tr>
  </thead>
    <% @contacts.each do |contact| %>
        <tr>
          <td>
            <%= contact.first_name %>
          </td>
          <td>
            <%= contact.last_name %>
          </td>
          <td>
            <%= contact.phone_number %>
          </td>
          <td>
            <%= contact.email %>
          </td>
          <td>
            <%= contact.street %> <%= contact.number %> <br />
            <%= contact.post_code %> <%= contact.city %>
          </td>
          <td>
            <%= link_to 'Edytuj', edit_contact_path(contact.id) %>
            <%= link_to 'Usuń', contact, method: :delete, data: { confirm: 'Czy jesteś pewien?'} %>
          </td>
        </tr>
  <% end %>
</table>
<%= will_paginate @contacts %>

<%= link_to 'Dodaj kontakt', new_contact_path, class: 'btn btn-default' %>

app/views/contacts/new.html.erb
<%= bootstrap_form_for(@contact) do |f| %>
    <%= f.hidden_field :users_id %>
    <%= f.text_field :first_name, label: 'Imię' %>
    <%= f.text_field :last_name, label: 'Nazwisko' %>
    <%= f.phone_field :phone_number, label: 'Nr telefonu' %>
    <%= f.email_field :email, label: 'Email' %>
    <%= f.text_field :street, label: 'Ulica' %>
    <%= f.text_field :number, label: 'Nr domu' %>
    <%= f.text_field :post_code, label: 'Kod pocztowy' %>
    <%= f.text_field :city, label: 'Miejscowość' %>
    <%= f.submit 'Dodaj' %>
    <%= link_to 'Powrót', contacts_path, class: 'btn btn-default' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Prosty CRM" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Prosty CRM</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Strona główna', contacts_path  %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
          <% if session[:current_user_id] %>
              <li><%= link_to 'Wyloguj się', logout_path  %></li>
          <% else %>
              <li><%= link_to 'Zaloguj się', login_path  %></li>
              <li><%= link_to 'Zarejestruj się', register_path  %></li>
          <% end %>
      </ul>
    </div>

  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

</div> <!-- /container -->

</body>
</html>